<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    public function image()
    {
        return $this->belongsTo(Image::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments(){
        return $this->hasMany(Comment::class)->where('publish',1);
    }

    public static function lastPost()
    {
        return Post::orderBy('created_at', 'desc')->take(2)->get();
    }

    public static function newsMore($count)
    {
        return Post::orderBy('created_at', 'desc')->take($count)->get();
    }
    public function getRouteKeyName()
    {
        return 'link'; // TODO: Change the autogenerated stub
    }
}
